export const testimonials = [
  {
    user: "Vijay Mali",
    date: "3 November 2023",
    content: "Game is joyful. Questions are interesting and easy to moderate level. App UI and other processing are smooth. If you're a cricket enthusiast then have a try once.",
    rating: 5,
  },
  {
    user: "Rishit Sah",
    date: "20 December 2023",
    content: "Awesome app, wonderful, simple and elegant, UI exp can be improved, facing a longer loading time and issues in OTP verification, onboarding can be made a lil smoother. Cheers guys.",
    rating: 5,
  },
  {
    user: "Ankit Giri",
    date: "5 November 2023",
    content: "Simple and elegant. Best way to make quick buck out of our cricket knowledge. Totally recommended!",
    rating: 5,
  },
  {
    user: "Shyam Sunder Bishnoi",
    date: "16 November 2023",
    content: "The thrill provides is really genuine. Can make UI better. This shows us simple can be good.",
    rating: 5,
  },
  {
    user: "Sunil Solanki",
    date: "2 November 2023",
    content: "I must say it has truly impressed me. The app lives up to its promise of being a genuine and fascinating way to earn money.",
    rating: 5,
  },
  {
    user: "Ankush Mittal",
    date: "5 November 2023",
    content: "I liked the zero commission part as best, Please allow us to increase the bet amount 😁 Also, would love to see more niche as Bollywood questions. I'm a Bollywood freak.",
    rating: 5,
  },
  {
    user: "Sunil Singh",
    date: "2 November 2023",
    content: "The app is amazing and specially the questions are so entertaining and engaging. Real enjoy playing this game.",
    rating: 5,
  },
  {
    user: "Garuda 444 YT",
    date: "6 November 2023",
    content: "It's genuine and very good for earning if you have cricket knowledge.",
    rating: 5,
  },
  {
    user: "Shailesh Hanmante",
    date: "4 November 2023",
    content: "One of the best games I have played recently. Amusing & Engaging experience. Finally can tell my Papa ki cricket se bhi Paisa Kama raha hoon 😅😅",
    rating: 5,
  },
  {
    user: "Prince Raj",
    date: "22 August 2023",
    content: "It offers a user-friendly interface, a wide range of betting options, and reliable payment methods. The app provides real-time updates on matches, odds, and scores, allowing users to make informed decisions. The betting process is smooth and hassle-free, making it enjoyable to use. Overall, this betting application is highly recommended for both novice and experienced bettors.",
    rating: 5,
  },
  {
    user: "Deepak Chahal",
    date: "2 November 2023",
    content: "Had smooth playing experience.",
    rating: 5,
  },
  {
    user: "Jitendra Patel",
    date: "10 November 2023",
    content: "Best way to double the money for the person with cricket knowledge",
    rating: 5,
  },
  {
    user: "Ankit",
    date: "5 November 2023",
    content: "This is a very good gaming app, working very smoothly. India's love for cricket makes this an entertaining and relaxing app. So all the 'cricket experts' make good use of your cricket knowledge and earn money here.",
    rating: 5,
  },
];
